// path: RankGateInsane/client/src/vm/bytecode.hpp
//
// Declares the embedded, obfuscated VM bytecode blob. The bytes live in the
// generated bytecode_blob.cpp; vm.cpp decrypts them at runtime with a
// BLAKE2b-CTR keystream derived from VM_BLOB_KEY.
#pragma once

namespace rg::vm {

extern const unsigned char kEncryptedBlob[];
extern const unsigned long kEncryptedBlobLen;

}  // namespace rg::vm
