"""GENERATED by tools/generate_vm_bytecode.py -- do not edit by hand.

ENCRYPTED_BLOB is the canonical VM bytecode XOR-obfuscated with a BLAKE2b-CTR
keystream derived from config.VM_BLOB_KEY (domain config.VM_BLOB_DOMAIN). The
reference VM decrypts it in vm_reference.load_bytecode().
"""

ENCRYPTED_BLOB = bytes.fromhex(
    "308fe8b50021bcd8c01b4141399cd700089e24f0fb4a4aed04b9d9a515c7613c"
    "6086c650d07721972edb1a774715a935b4844f933662294aa0dad96357e048d6"
    "711ac886772f2f392d9a753c7525ee02d60aa813bc3a76d330a4dca97226aa2e"
    "8f055b198d722109c6f7e8836e318d706029f075d2cdbe4810f69450a090ea5c"
    "b851fcfee7a03bf1d72ae8a25870f34be8d9fb2f1e52bec2558531cb33264a57"
    "35485de1db8760a9dbfa26e661e33a185626881f9375839ad0b92314f192cb25"
    "6566f847a4c931778abc59a348df0839930af3ccbfc07ecf9a2171c51189ce49"
    "4cf5aa4e94c25e6afc7ad42056fec8342265"
)
