#!/usr/bin/env python3
"""Emit C++ byte-parity test vectors for the client crypto layer.

Runs the *server's own* crypto_box primitives over fixed inputs and prints a
generated C++ header (crypto_vectors.h) whose expected values the client
self-test must reproduce exactly. This is the contract that guarantees the
native client and the Python server compute byte-identical crypto.

    python tools/_gen_crypto_vectors.py > client/tests/crypto_vectors.h
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "server"))

from app import config              # noqa: E402
from app import crypto_box as cb    # noqa: E402


def carr(name: str, data: bytes) -> str:
    body = ", ".join(f"0x{b:02x}" for b in data)
    return f"inline const std::vector<uint8_t> {name} = {{{body}}};"


def emit(lines: list[str]) -> None:
    print("\n".join(lines))


# Fixed inputs ---------------------------------------------------------------
KEY32 = bytes(range(32))                      # 00..1f
SALT32 = bytes((i * 7) & 0xFF for i in range(32))
IKM32 = bytes((i * 3 + 1) & 0xFF for i in range(32))
MSG = b"the quick brown fox"
DOMAIN = b"RG6-VEC-DOMAIN/v6"
INFO = b"RG6 vec info"

# X25519 fixed scalars
PRIV_A = bytes((i + 1) & 0xFF for i in range(32))
PRIV_B = bytes((255 - i) & 0xFF for i in range(32))
pub_b = cb.x25519_keypair(PRIV_B)[1]
shared = cb.x25519_shared(PRIV_A, pub_b)

# AEAD fixed
AKEY = bytes((i ^ 0x5A) & 0xFF for i in range(32))
ANONCE = bytes((i + 0x10) & 0xFF for i in range(24))
APLAIN = b"RankGate sealed payload \x00\x01\x02 end"
AAD = b"RG6-aad-header"
act, atag = cb.aead_encrypt(AKEY, ANONCE, APLAIN, AAD)

# Ed25519: sign with the server signing key, verify in C++.
ed_msg = b"RG6-server-challenge-bytes"
ed_sig = cb.ed25519_sign(config.SERVER_SIGN_SK, ed_msg)
ed_pk = config.SERVER_SIGN_PK

out = [
    "// GENERATED by tools/_gen_crypto_vectors.py -- do not edit by hand.",
    "// Byte-parity contract between the Python server and the C++ client.",
    "#pragma once",
    "#include <cstdint>",
    "#include <vector>",
    "",
    "namespace rg::vectors {",
    "",
    carr("kKey32", KEY32),
    carr("kSalt32", SALT32),
    carr("kIkm32", IKM32),
    carr("kMsg", MSG),
    carr("kDomain", DOMAIN),
    carr("kInfo", INFO),
    "",
    "// SHA-256",
    carr("kSha256_T0", cb.sha256(config.TRANSCRIPT_SEED)),
    carr("kSha256_Msg", cb.sha256(MSG)),
    "",
    "// BLAKE2b (unkeyed 32, keyed 32->4, keyed 32->64)",
    carr("kBlake_Unkeyed32", cb.blake2b(MSG, size=32)),
    carr("kBlake_Keyed4", cb.blake2b(MSG, key=KEY32, size=4)),
    carr("kBlake_Keyed64", cb.blake2b(MSG, key=KEY32, size=64)),
    "",
    "// HMAC-SHA256",
    carr("kHmac", cb.hmac_sha256(KEY32, MSG)),
    "",
    "// HKDF-SHA256 (extract+expand, 48 bytes)",
    carr("kHkdf48", cb.hkdf(SALT32, IKM32, INFO, 48)),
    "",
    "// BLAKE2b-CTR keystream (80 bytes) and stream_xor",
    carr("kKeystream80", cb.blake2b_ctr_keystream(KEY32, 80, domain=DOMAIN)),
    carr("kStreamXor", cb.stream_xor(KEY32, MSG, domain=DOMAIN)),
    "",
    "// X25519: pub(PRIV_B) and shared(PRIV_A, pub_b)",
    carr("kPrivA", PRIV_A),
    carr("kPrivB", PRIV_B),
    carr("kPubB", pub_b),
    carr("kShared", shared),
    "",
    "// XChaCha20-Poly1305 IETF: key/nonce/aad/plain -> ct, tag",
    carr("kAeadKey", AKEY),
    carr("kAeadNonce", ANONCE),
    carr("kAeadAad", AAD),
    carr("kAeadPlain", APLAIN),
    carr("kAeadCt", act),
    carr("kAeadTag", atag),
    "",
    "// Ed25519: pk/msg/sig (must verify true)",
    carr("kEdPk", ed_pk),
    carr("kEdMsg", ed_msg),
    carr("kEdSig", ed_sig),
    "",
    "}  // namespace rg::vectors",
]
emit(out)
