#!/usr/bin/env python3
"""Emit C++ VM parity vectors from the Python reference VM.

Runs server/app/vm_reference.run_vm over fixed inputs and prints a header the
client VM self-test compares against. The Python side uses the server's
bytecode blob; the C++ side uses its own embedded blob -- agreement proves both
the engine and the blob match.

    python tools/_gen_vm_vectors.py > client/tests/vm_vectors.h
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "server"))

from app import verifier        # noqa: E402
from app import vm_reference    # noqa: E402


def carr(name: str, data: bytes) -> str:
    body = ", ".join(f"0x{b:02x}" for b in data)
    return f"inline const std::vector<uint8_t> {name} = {{{body}}};"


USERNAME = b"player1"
LICENSE = verifier.build_license_struct(USERNAME)
SERVER_RANDOM = bytes((i * 5 + 2) & 0xFF for i in range(16))
SESSION_ID = bytes((i * 9 + 1) & 0xFF for i in range(16))
TRANSCRIPT_PREFIX = bytes((i * 11 + 3) & 0xFF for i in range(32))

res = vm_reference.run_vm(USERNAME, LICENSE, SERVER_RANDOM, SESSION_ID,
                          TRANSCRIPT_PREFIX, SERVER_RANDOM)

out = [
    "// GENERATED by tools/_gen_vm_vectors.py -- do not edit by hand.",
    "#pragma once",
    "#include <cstdint>",
    "#include <vector>",
    "",
    "namespace rg::vmvec {",
    "",
    carr("kUsername", USERNAME),
    carr("kLicense", LICENSE),
    carr("kServerRandom", SERVER_RANDOM),
    carr("kSessionId", SESSION_ID),
    carr("kTranscriptPrefix", TRANSCRIPT_PREFIX),
    "",
    carr("kVmDigest", res.vm_digest),
    carr("kVmStateHash", res.vm_state_hash),
    f"inline const uint32_t kVmPathId = 0x{res.vm_path_id:08x};",
    f"inline const uint32_t kVmHaltCode = 0x{res.vm_halt_code:08x};",
    "",
    "}  // namespace rg::vmvec",
]
print("\n".join(out))
