#!/usr/bin/env python3
"""Author-side generator for the RG6 standalone crackme sealed flag.

Mirrors crackme/crypto/keyschedule.cpp exactly, encrypts the real flag with the
password-derived key, and emits crackme/protection/encrypted_flag.hpp. The real
flag and real password never appear in the compiled binary -- only the AEAD
blob (nonce || ciphertext || tag) does, and it only decrypts under the correct
password-derived key.

Phase A: the key depends on the password alone. Later phases extend the IKM and
switch the HKDF salt to the VM digest; update the matching constants in both
this file and keyschedule.cpp together, then regenerate.

Usage:
    python tools/generate_flag_blob.py            # use built-in defaults
    python tools/generate_flag_blob.py --password "..." --flag "FLAG{...}"
"""
import argparse
import hashlib
import hmac
import os

from nacl.bindings import crypto_aead_xchacha20poly1305_ietf_encrypt as aead_encrypt

# --- domain constants: MUST match crackme/crypto/keyschedule.hpp -------------
PW_NORM_KEY = b"RG6-pwd-norm-v1"
DOMAIN_SEPARATOR = b"RG6|standalone|final-flag-seal|v2"
HKDF_SALT = b"RG6-final-seal-salt-phaseA-v2"
HKDF_INFO = b"RG6 final flag seal v2"
FLAG_AAD = b"RG6-flag-aad-v2"

# Author defaults. The password is the secret later phases will hide; for now it
# is simply the seed of the flag-encryption key and is NOT stored in the binary.
DEFAULT_PASSWORD = "S1lentP4ssage::HaloGate#2026"
DEFAULT_FLAG = "FLAG{rg6_standalone_phaseA_password_sealed_seal}"

WS = b" \t\r\n\x0b\x0c"


def normalize_password(raw: str) -> bytes:
    return raw.encode("utf-8").strip(WS)


def hkdf_sha256(salt: bytes, ikm: bytes, info: bytes, length: int) -> bytes:
    prk = hmac.new(salt, ikm, hashlib.sha256).digest()
    okm, t, c = b"", b"", 1
    while len(okm) < length:
        t = hmac.new(prk, t + info + bytes([c]), hashlib.sha256).digest()
        okm += t
        c += 1
    return okm[:length]


def derive_final_key(normalized_password: bytes) -> bytes:
    npw_hash = hashlib.blake2b(normalized_password, key=PW_NORM_KEY, digest_size=32).digest()
    ikm = hashlib.blake2b(npw_hash + DOMAIN_SEPARATOR, digest_size=64).digest()
    return hkdf_sha256(HKDF_SALT, ikm, HKDF_INFO, 32)


def emit_header(blob: bytes) -> str:
    rows = []
    for i in range(0, len(blob), 12):
        rows.append("    " + ", ".join(f"0x{b:02x}" for b in blob[i:i + 12]) + ",")
    body = "\n".join(rows)
    return f"""// path: crackme/protection/encrypted_flag.hpp
//
// GENERATED by tools/generate_flag_blob.py -- do not edit by hand.
// Layout: nonce(24) || ciphertext || Poly1305 tag(16).
// Decrypts only under the correct password-derived key (see keyschedule.cpp).
#pragma once

#include <cstddef>
#include <cstdint>

namespace rg6 {{

inline constexpr std::size_t kFlagBlobLen = {len(blob)};
inline constexpr unsigned char kFlagBlob[kFlagBlobLen] = {{
{body}
}};

}}  // namespace rg6
"""


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--password", default=DEFAULT_PASSWORD)
    ap.add_argument("--flag", default=DEFAULT_FLAG)
    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    default_out = os.path.join(here, "crackme", "protection", "encrypted_flag.hpp")
    ap.add_argument("--out", default=default_out)
    args = ap.parse_args()

    key = derive_final_key(normalize_password(args.password))
    nonce = os.urandom(24)
    combined = aead_encrypt(args.flag.encode("utf-8"), FLAG_AAD, nonce, key)
    blob = nonce + combined

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w", encoding="utf-8", newline="\n") as f:
        f.write(emit_header(blob))
    print(f"wrote {args.out} ({len(blob)} bytes; flag={len(args.flag)} chars)")


if __name__ == "__main__":
    main()
